### ISSUE TITLE
Support for new hash for RST files

### ISSUE THREAD

**Issue by GuiSaiUwU** [Noisrev/rion#5]
From start of patch 14.15 riot started to use [xxh3](https://github.com/CommunityDragon/CDTB/commit/714553c95fbb217356d2d87a3946a0dd652608ff)
Currently when you convert RST with rion there is no hashes
Any plans of support new RST?
![image](https://github.com/user-attachments/assets/ac78a4ce-945c-42c9-999e-333de92183c5)

**Comment by Roshaless** [comment]
@GuiSaiUwU I see. And I complete it at two weeks ago (for new rst).


But this is not used full xxh3 generated hash, it is "trimmed xxh3 hash" (i get a way to trim the xxh3 hash, and test it, that is right).


Also, I lost my original account's 2FA and recovery-code, so that account is not available.

This is my new account ;-;
So, I well be push updates in new repo.
But I've been focusing on other work lately, so I may not be able to update, but it won't be long.😉

**Comment by GuiSaiUwU** [comment]
thats sad ;-; I will close this here hope u update in new account
